modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbxmodcompat"
version = "${version}"
displayName = "FTB XMod Compat"
authors = "FTB Team"
description = '''
Provides cross-mod compatibilty/integration for all main FTB mods
'''
#logoFile = ""

[[dependencies.ftbxmodcompat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftblibrary"
mandatory = true
versionRange = "[2001.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftbquests"
mandatory = false
versionRange = "[2001.1.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftbchunks"
mandatory = false
versionRange = "[2001.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "kubejs"
mandatory = false
versionRange = "[1902.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "jei"
mandatory = false
versionRange = "[15.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftbranks"
mandatory = false
versionRange = "[2001.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "kubejs"
mandatory = false
versionRange = "[1902.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "luckperms"
mandatory = false
versionRange = "[5.4.83,)"
ordering = "AFTER"
side = "SERVER"