modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbxmodcompat"
version = "${version}"
displayName = "FTB XMod Compat"
authors = "FTB Team"
description = '''
Provides cross-mod compatibilty/integration for all main FTB mods
'''
#logoFile = ""

[[dependencies.ftbxmodcompat]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1902.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "ftbquests"
mandatory = false
versionRange = "[1902.5.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "kubejs"
mandatory = false
versionRange = "[1902.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbxmodcompat]]
modId = "jei"
mandatory = false
versionRange = "[11.6,)"
ordering = "AFTER"
side = "BOTH"